const data = [{
        title: "FREE",
        price: 0,
        users: { title: "Single User", boldFlag: false },
        storage: "5GB",
        publicProjects: "Unlimited Public Projects",
        communityAccess: "Community Access",
        privateProjects: { title: "Unlimited Private Projects", flag: false },
        phoneSupport: { title: "Dedicated Phone Support", flag: false },
        subdomain: { title: "Free Subdomain", flag: false },
        statusReport: { title: "Monthly Status Reports", flag: false },
    },
    {
        title: "PLUS",
        price: 9,
        users: { title: "5 Users", boldFlag: true },
        storage: "50GB",
        publicProjects: "Unlimited Public Projects",
        communityAccess: "Community Access",
        privateProjects: { title: "Unlimited Private Projects", flag: true },
        phoneSupport: { title: "Dedicated Phone Support", flag: true },
        subdomain: { title: "Free Subdomain", flag: true },
        statusReport: { title: "Monthly Status Reports", flag: false },
    },
    {
        title: "PRO",
        price: 49,
        users: { title: "Unlimited Users", boldFlag: true },
        storage: "150GB",
        publicProjects: "Unlimited Public Projects",
        communityAccess: "Community Access",
        privateProjects: { title: "Unlimited Private Projects", flag: true },
        phoneSupport: { title: "Dedicated Phone Support", flag: true },
        subdomain: { title: "Free Subdomain", flag: true, subTitle: "Unlimited" },
        statusReport: { title: "Monthly Status Reports", flag: true },
    },
];

export default data;